import {
  PAYMENT_PERMISSION_KEYS,
  FINANCE_PERMISSION_KEYS,
  METERS_PERMISSION_KEYS,
  PERMISSION_KEYS,
} from '@rpm/contracts';

export { hasPermission, canMutate } from '@/features/admin/utils/permissions';

export const FINANCE_PERMISSIONS = {
  chargesCreate: FINANCE_PERMISSION_KEYS.CHARGES_CREATE,
  chargesUpdate: FINANCE_PERMISSION_KEYS.CHARGES_UPDATE,
  chargesVoid: FINANCE_PERMISSION_KEYS.CHARGES_VOID,
  invoicesList: FINANCE_PERMISSION_KEYS.INVOICES_LIST,
  invoicesView: FINANCE_PERMISSION_KEYS.INVOICES_VIEW,
  invoicesIssue: FINANCE_PERMISSION_KEYS.INVOICES_ISSUE,
  billingRunPreview: FINANCE_PERMISSION_KEYS.BILLING_RUN_PREVIEW,
  billingRunCommit: FINANCE_PERMISSION_KEYS.BILLING_RUN_COMMIT,
  depositsView: FINANCE_PERMISSION_KEYS.DEPOSITS_VIEW,
  depositsRecord: FINANCE_PERMISSION_KEYS.DEPOSITS_RECORD,
  depositsDisposition: PAYMENT_PERMISSION_KEYS.DEPOSITS_DISPOSITION,
  depositsDispose: PAYMENT_PERMISSION_KEYS.DEPOSITS_DISPOSE,
  creditNotesCreate: FINANCE_PERMISSION_KEYS.CREDIT_NOTES_CREATE,
  creditNotesPost: FINANCE_PERMISSION_KEYS.CREDIT_NOTES_POST,
  reportsView: FINANCE_PERMISSION_KEYS.REPORTS_VIEW,
  paymentsList: PAYMENT_PERMISSION_KEYS.LIST,
  paymentsView: PAYMENT_PERMISSION_KEYS.VIEW,
  paymentsRecord: PAYMENT_PERMISSION_KEYS.RECORD,
  paymentsAllocate: PAYMENT_PERMISSION_KEYS.ALLOCATE,
  refundsRequest: PAYMENT_PERMISSION_KEYS.REFUNDS_REQUEST,
  refundsApprove: PAYMENT_PERMISSION_KEYS.REFUNDS_APPROVE,
  refundsExecute: PAYMENT_PERMISSION_KEYS.REFUNDS_EXECUTE,
  depositsDispositionApprove: PAYMENT_PERMISSION_KEYS.DEPOSITS_DISPOSITION_APPROVE,
  reconciliationView: PERMISSION_KEYS.FINANCE_RECONCILIATION_VIEW,
  reconciliationPerform: PERMISSION_KEYS.FINANCE_RECONCILIATION_PERFORM,
  reconciliationApprove: PERMISSION_KEYS.FINANCE_RECONCILIATION_APPROVE,
  periodClose: PERMISSION_KEYS.FINANCE_PERIOD_CLOSE,
  exportsCreate: PERMISSION_KEYS.FINANCE_EXPORTS_CREATE,
} as const;

export const METERS_PERMISSIONS = {
  list: METERS_PERMISSION_KEYS.LIST,
  view: METERS_PERMISSION_KEYS.VIEW,
  create: METERS_PERMISSION_KEYS.CREATE,
  update: METERS_PERMISSION_KEYS.UPDATE,
  readingsRecord: METERS_PERMISSION_KEYS.READINGS_RECORD,
  readingsBulk: METERS_PERMISSION_KEYS.READINGS_BULK,
} as const;

export const UTILITIES_PERMISSIONS = {
  allocate: PERMISSION_KEYS.UTILITIES_ALLOCATE,
} as const;
